version: "3.8"
services:
  task:
    build:
      context: internal
      args:
        SERVICE: task
    volumes:
      - ./internal:/internal
    working_dir: /internal/task
    ports:
      - "50051:50051"
    env_file:
      - .env
    depends_on:
      - postgres

  user:
    build:
      context: internal
      args:
        SERVICE: user
    volumes:
      - ./internal:/internal
    working_dir: /internal/user
    ports:
      - "50053:50053"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    build: 
      context: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
