version: "3.8"
services:
  task:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
    working_dir: /internal/task
    ports:
      - "50051:$TASK_GRPC_PORT"
    env_file:
      - .env
    depends_on:
      - mongo

  user:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
    working_dir: /internal/user
    ports:
      - "50053:$USER_GRPC_PORT"
    env_file:
      - .env
    depends_on:
      - mongo

  client:
    build:
      context: docker/app
    volumes: 
      - ./internal/common:/internal/common
    working_dir: /internal/common/client
    ports: 
      - "8000:8000"
    env_file:
      - .env

  mongo:
    image: mongo:4.0.27-rc0-xenial
    restart: always
    ports:
      - "27017:27017"
    volumes: 
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
