version: "3.7"
services:
  task:
    build:
      context: ./
      dockerfile: /internal/task/Dockerfile
    image: task-grpc
    container_name: task
    ports:
      - "50051:50051"

  db:
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: drifterz13
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test
      
