version: "3.8"
services:
  task:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
    working_dir: /internal/task
    ports:
      - "50051:50051"
    env_file:
      - .env
    depends_on:
      - mongo

  user:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
    working_dir: /internal/user
    ports:
      - "50053:50053"
    env_file:
      - .env
    depends_on:
      - mongo

  # postgres:
  #   build: 
  #     context: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres/data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_PORT: ${POSTGRES_PORT}

  mongo:
    image: mongo:4.0.27-rc0-xenial
    restart: always
    ports:
      - "27017:27017"
    volumes: 
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
