version: "3.8"
services:
  task:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
    working_dir: /internal/task
    ports:
      - "50051:50051"
    env_file:
      - .env
    depends_on:
      - mongo

  user:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
    working_dir: /internal/user
    ports:
      - "50053:50053"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0.27-rc0-xenial
    restart: always
    ports:
      - "27017:27017"
    volumes: 
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
